worker_processes auto;

pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  # Logging
  access_log /dev/stdout;
  error_log /dev/stderr warn;

  # Performance
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  keepalive_requests 1000;

  # Compression
  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_min_length 256;
  gzip_comp_level 6;
  gzip_types
    text/plain
    text/css
    text/xml
    text/javascript
    application/javascript
    application/x-javascript
    application/json
    application/xml
    application/xml+rss
    font/ttf
    font/otf
    image/svg+xml;

  # leoflo.me instance
  server {
    listen 8001;
    server_name _;

    root /srv/leoflo.me;
    index index.html;
  }

  # cgit instance
  server {
    listen 8002;
    server_name _;

    root /srv/cgit;
    try_files $uri @cgit;

    location ~ /.+/(info/refs|git-upload-pack) {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME /usr/lib/git-core/git-http-backend;
      fastcgi_param PATH_INFO $uri;
      fastcgi_param GIT_HTTP_EXPORT_ALL 1;
      fastcgi_param GIT_PROJECT_ROOT /srv/git;
      fastcgi_param HOME /srv/git;
      fastcgi_pass unix:/run/fcgiwrap.sock;
    }

    location @cgit {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME /srv/cgit/cgit.cgi;
      fastcgi_param PATH_INFO $uri;
      fastcgi_param QUERY_STRING $args;
      fastcgi_param HTTP_HOST $server_name;
      fastcgi_pass unix:/run/fcgiwrap.sock;
    }
  }
}
